SOVSUB/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

from appmain import urls as appmain_urls
from users import urls as users_urls
from miner import urls as miner_urls

admin.site.site_header = "SOVSUB Admin"
admin.site.site_title = "SOVSUB Admin Portal"
admin.site.index_title = "Welcome to SOVSUB Admin Portal"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(appmain_urls)),
    path('miner/', include(miner_urls)),
    path('user/', include(users_urls)),
]

miner/urls.py
from django.urls import path

from .views import update_transaction
from .views import set_new_transaction
from .views import get_chain
from .views import mine_unconfirmed_transactions
from .views import register_new_peers
from .views import register_with_existing_node
from .views import verify_and_add_block
from .views import get_pending_tx

urlpatterns = [
    path('update_transaction/', update_transaction, name='update_transaction'),
    path('new_transaction/', set_new_transaction, name='set_new_transaction'),
    path('chain/', get_chain, name='get_chain'),
    path('mine/', mine_unconfirmed_transactions, name='mine_unconfirmed_transactions'),
    path('register_node/', register_new_peers, name='register_new_peers'),
    path('register_with/', register_with_existing_node, name='register_with_existing_node'),
    path('add_block/', verify_and_add_block, name='verify_and_add_block'),
    path('pending_tx/', get_pending_tx, name='get_pending_tx'),
]

appmain/models.py
from django.db import models


# Create your models here.
class KeyModel(models.Model):
    temp_id = models.CharField(unique=True, max_length=256, blank=True)
    pukey = models.TextField(max_length=512, blank=True)
    voted = models.BooleanField(default=False)

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.core.validators import RegexValidator


class LoginForm(forms.Form):
    voter_id = forms.CharField(label='Voter ID', max_length=10, required=True)
    otp = forms.CharField(label='OTP', min_length=6, max_length=6, required=True)
    # image = forms.ImageField(label='Image')


class UserRegisterForm(UserCreationForm):
    username = forms.EmailField(max_length=100, required=True, label='E-mail')
    voter_id = forms.CharField(max_length=10)
    name = forms.CharField(max_length=100)
    booth_id = forms.CharField(max_length=10)
    phone_regex = RegexValidator(regex=r'^\+?\d{10,12}$',
                                 message='Phone number must be entered in the format: "+919876543210"')
    phone_number = forms.CharField(validators=[phone_regex], max_length=17)

    class Meta:
        model = User
        fields = ['username', 'voter_id', 'name', 'booth_id', 'phone_number']

    def __int__(self):
        self.fields['password1'].required = False
        self.fields['password2'].required = False

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>

    <style>
        html {
            height: 100%;
        }
        body {
            height: 100%;
            margin: 0;
            padding: 0;
            background-color:#5b8db1;
         }
        .container{
            width:100%;
            overflow-y: auto;
            height: 100%;
        }
        .contents-body{
            margin-top:20px;
            margin-bottom:20px;
        }
        .main_content{
            margin-top:20px;
            margin-bottom:20px;
            margin-left:30px;
            margin-right:30px;
        }
        .center-contain{
			margin-left: auto;
			margin-right: auto;
            margin-top:28px;
			position: relative;
			max-width: 540px;
			width: calc(100% - 40px);
			padding: 44px;
			margin-bottom: 28px;
			background-color: #fff;
			min-width: 320px;
			min-height: 338px;
			overflow: hidden;
		}
    </style>

    <title>SOVSUB</title>
</head>
<body>
    {% include 'nav_bar.html' %}
    <div class="container" style="height: 100%;">
        {% block content %}{% endblock %}
    </div>
</body>
</html>

templates/blockchain_page.html
{% block content %}
    <style>
        table {
          font-family: arial, sans-serif;
          border-collapse: collapse;
          width: 100%;
        }

        td, th {
          border: 1px solid #dddddd;
          text-align: center;
          padding: 8px;
        }

    </style>
    <table>
        <tr>
            <th>Block Id</th>
            <th>No. of transactions </th>
            <th>Time Stamp</th>
            <th>Block Hash</th>
        </tr>
        {% if blockchain %}
            {% for block in blockchain %}
            <tr>
                <td>{{block.height}}</td>
                <td>{{block.trans_len}}</td>
                <td>{{block.timestamp}}</td>
                <td>{{block.hash|truncatechars:50}}</td>
            </tr>
            {% endfor %}
        {% endif %}
    </table>
{% endblock content %}

templates/home_page.html
{% extends "base.html" %}
{% block content %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script>
           function loadOnButtonPress(link){
             $('#div_r').empty();
             $('#div_r').append('<div class="loader"></div>');
             $("#div_r").load( link );
           }
    </script>
    <style>
    .loader {
      border: 16px solid #f3f3f3;
      border-radius: 50%;
      border-top: 16px solid #3498db;
      width: 120px;
      height: 120px;
      -webkit-animation: spin 2s linear infinite; /* Safari */
      animation: spin 2s linear infinite;
    }

    /* Safari */
    @-webkit-keyframes spin {
      0% { -webkit-transform: rotate(0deg); }
      100% { -webkit-transform: rotate(360deg); }
    }

    @keyframes spin {
      0% { transform: rotate(0deg); }
      100% { transform: rotate(360deg); }
    }
    </style>
    <style>
        .split {
          height: 100%;
          position: fixed;
          z-index: 1;
          overflow-x: hidden;
          padding-top: 20px;
        }
        .left {
          left: 0;
          width:20%;
          background-color: #5b8db1;
          padding: 10px;
        }
        .right {
          right: 0;
          width:80%;
          background-color: #a0c7e4;
        }
    </style>
    <div class="" align="center">
        <div id="div_l" class="split left">
            {% if user.is_authenticated %}
                <button style="margin: 10px; " onclick=loadOnButtonPress("/reg/")><span class="glyphicon glyphicon-pencil"></span> Register Node</button>
                <br>
                <button style="margin: 10px; " onclick=loadOnButtonPress("/miner/mine/")><span class="glyphicon glyphicon-file"></span> Mine Transaction</button>
                <br>
                <button style="margin: 10px; " onclick=loadOnButtonPress("/pending_transaction_view/")><span class="glyphicon glyphicon-shopping-cart"></span> Pending Transaction</button>
            <br>
                <button style="margin: 10px; " onclick=loadOnButtonPress("/blockchain_view/")><span class="glyphicon glyphicon-link"></span> Blockchain</button>
            {% endif %}
        </div>

        <div class="split right">
            <div id="div_r" class="centered">
                <h2 class="media-heading">{{ head }}</h2>
                <p class="text-secondary">{{ message|linebreaksbr }}</p>
            </div>
        </div>
    </div>
{% endblock content %}

templates/intermediate_page.html
{% extends "base.html" %}
{% block content %}
    <form action="." method="post">
        {% csrf_token %}
        <input type="submit" name="op" value="vote_cast" />
        <input type="submit" name="op" value="register" />
        <input type="submit" name="op" value="election_result" />
        <input type="submit" name="op" value="transaction_view" />
    </form>
{% endblock content %}

templates/login_page.html
{% extends "base.html" %}
{% block content %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script>
        function generateOTP(){
            $('#id_otp').remove();
            var v_id = $('#id_voter_id').val();
            var csrf = '{{ csrf_token }}';
            var params = { 'csrfmiddlewaretoken' : csrf , 'voter_id' : v_id };

            $.ajax({
                type: 'POST',
                url : '/user/generate_otp/',
                data: params,
                success: function(data) {},
                error: function() {}
            })
            $('#otp_div').append('<input type="text" name="otp" maxlength="6" minlength="6" required="" id="id_otp">');
        }

        function loginForm(){
            var v_id = $('#id_voter_id').val();
            var otp = $('#id_otp').val();
            var csrf = '{{ csrf_token }}';
            var params = { 'csrfmiddlewaretoken' : csrf , 'otp' : otp, 'voter_id' : v_id };

            const video = document.querySelector('video');
            const mediaStream = video.srcObject;
            const tracks = mediaStream.getTracks();
            tracks.forEach(track => track.stop())

            setTimeout(function(){post('.', params)}, 1000);
        }

        function post(path, params, method='post') {
            const form = document.createElement('form');
            form.method = method;
            form.action = path;

            for (const key in params) {
                if (params.hasOwnProperty(key)) {
                  const hiddenField = document.createElement('input');
                  hiddenField.type = 'hidden';
                  hiddenField.name = key;
                  hiddenField.value = params[key];

                  form.appendChild(hiddenField);
                }
            }
            document.body.appendChild(form);
            form.submit(function(){
              $.post($(this).attr('action'), $(this).serialize(), function(response){
                    // do something here on success
              },'json');
              return false;
            });
        }
    </script>
    <div class="center-contain" align="center" style="background-color: #a0c7e4; border-radius: 20px; padding: 10px; margin-bottom: 28px; margin-top: 28px;">
            {% csrf_token %}
            <label for="id_voter_id">Voter ID:</label>
            <input type="text" name="voter_id" maxlength="10" required="" id="id_voter_id">
            <br>
            <div id="otp_div">
                <label for="id_otp">OTP:</label>
                <!input type="text" name="otp" maxlength="6" minlength="6" required="" id="id_otp">
                <button id="id_otp" onclick=generateOTP()>Generate OTP</button>
            </div>
            <br>
            <video autoplay id="videoElement" width="500px" height="375px" style="border:5px solid #1e472c;"></video>
            <script>
                var video = document.querySelector("#videoElement");

                if (navigator.mediaDevices.getUserMedia) {
                  navigator.mediaDevices.getUserMedia({ video: true })
                    .then(function (stream) {
                      video.srcObject = stream;
                    })
                    .catch(function (err0r) {
                      console.log("Something went wrong!");
                    });
                }
                video.srcObject = null;
                function stop(e) {
                  var stream = video.srcObject;
                  var tracks = stream.getTracks();

                  for (var i = 0; i < tracks.length; i++) {
                    var track = tracks[i];
                    track.stop();
                  }

                  video.srcObject = null;
                }
            </script>
            <br>
            <button onclick=loginForm()>Login</button>
    </div>
{% endblock content %}

templates/nav_bar.html
<style>
    .navbar{
        position: sticky;
        top: 0;
        z-index: 1071;
        margin-bottom: 2px;
        background-color: #2c5777;
    }
    .dropdown-menu{
      background-color: #808b96  ;
      border:1px solid #2f2f1e;
    }
    .dropdown-submenu {
      position: relative;
    }
    .dropdown-submenu .dropdown-menu {
      top: 0;
      left: 100%;
      margin-top: -1px;
    }
    $(document).ready(function(){
      $('.dropdown-submenu a.test').on("click", function(e){
        $(this).next('ul').toggle();
        e.stopPropagation();
        e.preventDefault();
      });
    });
</style>
<nav class="navbar navbar-inverse ">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'home' %}">SOVSUB</a>
        </div>

        <li class="collapse navbar-collapse" id="myNavbar">
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                    {% if not user.is_superuser %}
                        <li class="dropdown">
                            <a href="{% url 'vote_cast' %}" class="sub-sub-item" data-parent="#service">
                                <span class="glyphicon glyphicon-hand-up"></span> Cast Vote </a>
                        </li>
                        <li class="dropdown">
                            <a href="{% url 'register_to_vote_view' %}" class="sub-sub-item" data-parent="#service">
                                <span class="glyphicon glyphicon-ok-circle"></span> Register to Vote </a>
                        </li>
                    {% endif %}
                    <li class="dropdown">
                        <a href="{% url 'election_result' %}" class="sub-sub-item" data-parent="#service">
                            <span class="glyphicon glyphicon-eye-open"></span> View Result </a>
                   </li>
                    <li class="dropdown">
                        <a href="{% url 'transaction_view' %}" class="sub-sub-item" data-parent="#service">
                            <span class="glyphicon glyphicon-link"></span> View Transaction </a>
                    </li>

                    {% if user.is_superuser %}
                        <li>
                            <a href="/admin/"><span class="glyphicon glyphicon-user"></span> Admin Page</a>
                        </li>
                    {% endif %}
                    <li><a href="{% url 'logout_view' %}"><span class="glyphicon glyphicon-log-out"></span> Sign Out</a></li>
                {% else %}
                    <li><a href="{% url 'register_view' %}"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
                    <li><a href="{% url 'login_view' %}"><span class="glyphicon glyphicon-log-in"></span> Sign In</a></li>
                {% endif %}
            </ul>
        </li>
    </div>
</nav>

templates/pending_transaction_page.html
{% block content %}
    <style>
        table {
          font-family: arial, sans-serif;
          border-collapse: collapse;
          width: 100%;
        }

        td, th {
          border: 1px solid #dddddd;
          text-align: center;
          padding: 8px;
        }

    </style>
    <table>
        <tr>
            <th>Voter</th>
            <th>Voted</th>
            <th>Time Stamp</th>
            <th>Signature</th>
        </tr>
        {% if transactions %}
            {% for transaction in transactions %}
            <tr>
                <td>{{transaction.tempid}}</td>
                <td>{{transaction.voted}}</td>
                <td>{{transaction.timestamp}}</td>
                <td>{{transaction.signature|truncatechars:50}}</td>
            </tr>
            {% endfor %}
        {% endif %}
    </table>
{% endblock content %}

templates/register.html
<div class="grid">
    <form action="{% url 'reg' %}" method="POST" class="form votecast"> {% csrf_token %}

        <div class="input-group media">
            <span class="glyphicon glyphicon-link" ></span>
            <input type="text" name="register_with_node" placeholder="Node address" autofocus required id="register_with_node">
        </div>

        <button class="open-button btn btn-primary media" type="submit">Connect</button>
    </form>
</div>

templates/register_page.html
{% extends "base.html" %}
{% block content %}
<div class="center-contain" align="center"
     style="background-color: #a0c7e4; border-radius: 20px; padding: 10px; margin-bottom: 28px; margin-top: 28px;"
     xmlns="http://www.w3.org/1999/html">
        <form method="post">
            {% csrf_token %}
            <table>
            <tr><th><label for="id_username">E-mail:</label></th><td><input type="email" name="username" maxlength="100" autofocus required id="id_username"></td></tr>
            <tr><th><label for="id_voter_id">Voter id:</label></th><td><input type="text" name="voter_id" maxlength="10" required id="id_voter_id"></td></tr>
            <tr><th><label for="id_name">Name:</label></th><td><input type="text" name="name" maxlength="100" required id="id_name"></td></tr>
            <tr><th><label for="id_booth_id">Booth id:</label></th><td><input type="text" name="booth_id" maxlength="10" required id="id_booth_id"></td></tr>
            <tr><th><label for="id_phone_number">Phone number:</label></th><td><input type="text" name="phone_number" maxlength="17" required id="id_phone_number"></td></tr>
            <tr hidden><th><label for="id_password1">Password:</label></th><td><input type="password" value="hashWord@1" name="password1" autocomplete="new-password" required id="id_password1"><br></td></tr>
            <tr hidden><th><label for="id_password2">Password confirmation:</label></th><td><input type="password" value="hashWord@1" name="password2" autocomplete="new-password" required id="id_password2"><br></td></tr>
            </table>
            <button class="btn btn-primary media" type="submit">Sign Up</button>
        </form>
    </div>
{% endblock content %}

templates/result_page.html
{% extends "base.html" %}
{% block content %}
    <style>
        table {
          font-family: arial, sans-serif;
          border-collapse: collapse;
          width: 100%;
        }

        td, th {
          border: 1px solid #dddddd;
          text-align: center;
          padding: 8px;
        }

    </style>
    <table>
        <tr>
            <th>Serial no.</th>
            <th>Candidate Name</th>
            <!--th>Candidate Photo</th>
            <th>Electoral Symbol</th-->
            <th>Votes</th>
        </tr>
        {% if candidates %}
            {% for candidate in candidates %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{candidate.name}}</td>
                <!--td><img src="{{candidate.photo}}" alt="{{candidate.name}}" class="img-circle" style="width:80px; height:80px"></td>
                <td><img src="{{candidate.symbol}}" alt="{{candidate.party}}" class="img-circle" style="width:80px; height:80px"></td-->
                <td>{{candidate.vote}}</td>
            </tr>
            {% endfor %}
        {% endif %}
    </table>
{% endblock content %}

templates/transaction_page.html
{% extends "base.html" %}
{% block content %}
    <style>
        table {
          font-family: arial, sans-serif;
          border-collapse: collapse;
          width: 100%;
        }

        td, th {
          border: 1px solid #dddddd;
          text-align: center;
          padding: 8px;
        }

    </style>
    <table>
        <tr>
            <th>Block Id</th>
            <th>Voter</th>
            <th>Voted</th>
            <th>Time Stamp</th>
            <th>Signature</th>
        </tr>
        {% if transactions %}
            {% for transaction in transactions %}
            <tr>
                <td>{{transaction.block_Id}}</td>
                <td>{{transaction.tempid}}</td>
                <td>{{transaction.voted}}</td>
                <td>{{transaction.timestamp}}</td>
                <td>{{transaction.signature|truncatechars:50}}</td>
            </tr>
            {% endfor %}
        {% endif %}
    </table>
{% endblock content %}

templates/votecast_page.html
{% extends "base.html" %}
{% block content %}
    <!--<div class="grid">
        <form action="." method="POST" class="form votecast"> {% csrf_token %}

            <input type="text" name="tempid" placeholder="Temp ID" autofocus required id="id_tempid">
            <select class="btn " id="id_voted" name="voted" title="Candidate">
                <option selected="selected" value="nota">Nota</option>
                {% if candidates %}
                    {% for candidate in candidates %}
                        <option value={{candidate.candidate_id}}>{{candidate.name}}</option>
                    {% endfor %}
                {% endif %}
            </select>
            <input type="text" name="sk_hex" placeholder="Private key" autofocus required id="id_sk_hex">
            <input type="hidden" name="timestamp" placeholder="Time stamp" id="id_timestamp">
            <script>
                var d = new Date();
                document.getElementById("id_timestamp").value  = + d;
            </script>

            <button class="open-button btn btn-primary media" type="submit">Vote</button>
        </form>
    </div>-->
<style>
    .loader {
      border: 16px solid #f3f3f3;
      border-radius: 50%;
      border-top: 16px solid #3498db;
      width: 120px;
      height: 120px;
      -webkit-animation: spin 2s linear infinite; /* Safari */
      animation: spin 2s linear infinite;
    }

    /* Safari */
    @-webkit-keyframes spin {
      0% { -webkit-transform: rotate(0deg); }
      100% { -webkit-transform: rotate(360deg); }
    }

    @keyframes spin {
      0% { transform: rotate(0deg); }
      100% { transform: rotate(360deg); }
    }
    </style>
    <style>
        .split {
          height: 100%;
          position: fixed;
          z-index: 1;
          overflow-x: hidden;
          padding-top: 20px;
        }
        .left {
          left: 0;
          width:70%;
          background-color: #5b8db1;
          padding: 10px;
        }
        .right {
          right: 0;
          width:30%;
          background-color: #a0c7e4;
        }
        table {
          font-family: arial, sans-serif;
          border-collapse: collapse;
          width: 100%;
        }

        td, th {
          border: 1px solid #dddddd;
          text-align: center;
          padding: 8px;
        }

    </style>
    <script>
        function assignVoted(voted)
        {
            document.getElementById('id_voted').value=voted;
        }
    </script>
    <div class="" align="center">
        <div id="div_l" class="split left">
            <table>
                <tr>
                    <th>Serial no.</th>
                    <th>Candidate Name</th>
                    <!--th>Candidate Photo</th>
                    <th>Electoral Symbol</th-->
                    <th>Your Vote</th>
                </tr>
                {% if candidates %}
                    {% for candidate in candidates %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>
                            <div class="radiotext">
                                <label for='{{candidate.candidate_id}}'>{{candidate.name}}</label>
                            </div>
                        </td>
                        <!--td><img src="{{candidate.photo}}" alt="{{candidate.name}}" class="img-circle" style="width:80px; height:80px"></td>
                        <td><img src="{{candidate.symbol}}" alt="{{candidate.party}}" class="img-circle" style="width:80px; height:80px"></td-->
                        <td>
                            <div class="radio">
                                <label><input onclick=assignVoted("{{candidate.candidate_id}}") type="radio" id='{{candidate.candidate_id}}' name="optradio"></label>
                            </div>
                        </td>
                    </tr>
                    {% endfor %}
                {% endif %}
            </table>
        </div>

        <div class="split right">
            <div id="div_r" class="centered">
                <form action="." method="POST" class="form votecast"> {% csrf_token %}

                    <input type="text" name="tempid" placeholder="Temp ID" autofocus required id="id_tempid">
                    <input id="id_voted" type="text" name="voted" placeholder="Candidate" hidden>
                    <input type="text" name="sk_hex" placeholder="Private key" autofocus required id="id_sk_hex">
                    <input type="hidden" name="timestamp" placeholder="Time stamp" id="id_timestamp">
                    <script>
                        var d = new Date();
                        document.getElementById("id_timestamp").value  = + d;
                    </script>

                    <button class="open-button btn btn-primary media" type="submit">Vote</button>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}

templates/webcam.html
<html>
     <head>
         <meta charset="utf-8" />
         <title>Webcam</title>
         <style>
             #videoElement {
               border: 30px solid #ccc;
               background: green;
               width: 400px;
               height: 400px
              }
         </style>
     </head>
     <body>
       <button>Start camera</button>
           <br/>
           <video autoplay="true" id="videoElement"></video>

           <script type="text/javascript">
                var video = document.querySelector("#videoElement");
                navigator.getUserMedia = navigator.getUserMedia || navigator.webkitGetUsermedia
                    || navigator.mozGetUserMedia || navigato.msGetUserMedia || navigator.oGetUserMedia;

                    if(navigator.getUserMedia){
                      navigator.getUserMedia({video:true}, handleVideo, videoError)
                    }

                    function handleVideo(stream){
                    video.srcObject = stream;
                    video.play();
                    }

                    function videoError(e){}
           </script>
     </body>
</html>